sys:
  student:
    roleid:
      "role_id_xs"
  debug:
    #DEBUG开关
    switch:
      ${app.debug.switch}
  #ignoreLogin 是否忽略注释 true、false
  ignoreLogin:
    switch:
      ${app.ignore.switch}
    userId:
      "20112026"
#      "127506"
    userType:
      "3"
#      "1"
  cache:
    mapperbeans:
      dmHzlxMapper,dmZhpjMapper,dmYyMapper,dmCgSqlxMapper,dmYnMapper,dmHylxMapper,dmGbMapper,dmXbMapper,dmCfmdMapper,dmCgspjgMapper,dmHzztMapper,dmJflyMapper,dmJhlxMapper,dmLfmdMapper,dmTzjbMapper,dmTzlbMapper,dmWblfJdlxMapper,dmXmccMapper,dmXmlxMapper,dmXmmcMapper,dmZzskMapper
  upload:
    #上传文件的基本路径
    base_dir:
      ######### 本地开发环境  ##############
      D:\\upload\\
      ########    121测试环境   ##############
      #/mntdata/picdir/exchange
      #######   上线前UAT测试环境  ###########
#      /home/weblogic/upload/
  access:
    #忽略访问，ext为忽略扩展名，url，为忽略路径
    ignore:
      ext:
        css,js,png,gif,jpg,woff,woff2,otf,svg,ttf,eot
      url:
