###############################################################
##    开发人员注意此文件中出现${}  会经过maven根据环境替换        ##
###############################################################
sys:
  student:
    roleid:
      "role_id_xs"
  debug:
    #DEBUG开关
    switch:
      ${app.debug.switch}
  #ignoreLogin 是否忽略注释 true、false
  ignoreLogin:
    switch:
      ${app.ignoreLogin.switch}
    userId:
      "20112026"
#      "127506"
    userType:
      "3"
#      "1"
  cache:
    mapperbeans:
      dmWjjsqzMapper,dmCcxzMapper,dmHzlxMapper,dmZhpjMapper,dmYyMapper,dmCgSqlxMapper,dmYnMapper,dmHylxMapper,dmGbMapper,dmXbMapper,dmCfmdMapper,dmCgspjgMapper,dmHzztMapper,dmJflyMapper,dmJhlxMapper,dmLfmdMapper,dmTzjbMapper,dmTzlbMapper,dmWblfJdlxMapper,dmXmccMapper,dmXmlxMapper,dmXmmcMapper,dmZzskMapper
  upload:
    #上传文件的基本路径
    base_dir:
      ${app.upload.base_dir}
  access:
    #忽略访问，ext为忽略扩展名，url，为忽略路径
    ignore:
      ext:
        css,js,png,gif,jpg,woff,woff2,otf,svg,ttf,eot
      url:

wx_interface:
  switch:
    ${ifs.wechat.switch}
  debug:
    ${ifs.wechat.debug}
  debugReceiveUser:
    ${ifs.wechat.debugReceiveUser}
  postUrl:
    http://i.cmu.edu.cn/dcp/ifs
  sysId:
    wxpt_gjjl
  key:
    lbhunpuwgwaoanmbtsszqgrv